# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog, QMessageBox, QScrollBar, QLabel, QAbstractItemView
from PyQt5.QtGui import QBrush, QColor, QFont, QDesktopServices
from PyQt5.QtCore import QThread, pyqtSignal, QUrl
from PyQt5.QtCore import Qt

import time
import os

import ctypes

ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")


class DraggableLabel(QLabel):
    def __init__(self, parent=None):
        super().__init__(parent)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.offset = event.pos()

    def mouseMoveEvent(self, event):
        if event.buttons() & Qt.LeftButton:
            # 计算移动后的窗口位置
            window_pos = self.parent().pos() + event.pos() - self.offset
            self.parent().move(window_pos)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1600, 900)
        ico_path = './icon/app.jpg'
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ico_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        font = QtGui.QFont()
        font.setFamily("仿宋")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(41, 50, 57);")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        # 设置无边框窗口
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(10, 60, 371, 821))
        self.frame_menu.setMouseTracking(False)
        self.frame_menu.setStyleSheet("background-color: rgb(54, 63, 70);\n"
                                      "border-radius: 15px;")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.pushButton_start = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_start.setGeometry(QtCore.QRect(130, 490, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        # self.pushButton_start.setStyleSheet("background-color: rgb(98, 157, 235);"
        #                                     "border-radius: 15px;"
        #                                     "color: rgb(255, 255, 255);")

        button_style = (
            "QPushButton {"
            "background-color: rgb(98, 157, 235);"
            "border-radius: 15px;"
            "color: rgb(255, 255, 255);"
            # "border: 4px solid rgb(60, 96, 144);"  # 设置边框

            "}"
            "QPushButton:hover {"
            "background-color: rgb(74, 117, 176);"
            "}"
            "QPushButton:pressed {"
            "background-color: rgb(60, 96, 144);"
            "}"
        )

        # 设置按钮样式
        self.pushButton_start.setStyleSheet(button_style)

        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_export = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_export.setGeometry(QtCore.QRect(130, 540, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export.setFont(font)
        # 设置按钮样式
        self.pushButton_export.setStyleSheet(button_style)

        self.pushButton_export.setObjectName("pushButton_export")
        self.label_10 = QtWidgets.QLabel(self.frame_menu)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 371, 201))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("icon/icon.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_26 = QtWidgets.QLabel(self.frame_menu)
        self.label_26.setGeometry(QtCore.QRect(100, 730, 211, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setToolTipDuration(-1)
        self.label_26.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                    "\n"
                                    "border-radius: 7px;\n"
                                    "\n"
                                    "color: rgb(151, 155, 158);")
        self.label_26.setText("")
        self.label_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_26.setObjectName("label_26")
        self.pushButton_dir = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_dir.setGeometry(QtCore.QRect(18, 240, 45, 45))
        self.pushButton_dir.setStyleSheet("QPushButton:hover { background-color: rgb(98, 105, 111); }")
        self.pushButton_dir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dir.setIcon(icon)
        self.pushButton_dir.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_dir.setObjectName("pushButton_dir")
        self.pushButton_video = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_video.setGeometry(QtCore.QRect(18, 293, 45, 45))
        self.pushButton_video.setStyleSheet("QPushButton:hover { background-color: rgb(98, 105, 111); }")
        self.pushButton_video.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video.setIcon(icon1)
        self.pushButton_video.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_video.setObjectName("pushButton_video")
        self.pushButton_img = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_img.setGeometry(QtCore.QRect(18, 355, 45, 45))
        self.pushButton_img.setStyleSheet("QPushButton:hover { background-color: rgb(98, 105, 111); }")
        self.pushButton_img.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/dirs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_img.setIcon(icon2)
        self.pushButton_img.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_img.setObjectName("pushButton_img")
        self.pushButton_cam = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_cam.setGeometry(QtCore.QRect(18, 411, 45, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cam.sizePolicy().hasHeightForWidth())
        self.pushButton_cam.setSizePolicy(sizePolicy)
        self.pushButton_cam.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_cam.setStyleSheet("QPushButton:hover { background-color: rgb(98, 105, 111); }")
        self.pushButton_cam.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/cam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cam.setIcon(icon3)
        self.pushButton_cam.setIconSize(QtCore.QSize(40, 27))
        self.pushButton_cam.setCheckable(False)
        self.pushButton_cam.setAutoRepeat(False)
        self.pushButton_cam.setAutoRepeatDelay(300)
        self.pushButton_cam.setObjectName("pushButton_cam")
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setGeometry(QtCore.QRect(70, 250, 280, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setToolTipDuration(-1)
        self.label.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                 "padding-left: 5px;"
                                 "border-radius: 7px;\n"
                                 "\n"
                                 "color: rgb(151, 155, 158);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_menu)
        self.label_3.setGeometry(QtCore.QRect(70, 361, 280, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(-1)
        self.label_3.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                   "padding-left: 5px;"
                                   "border-radius: 7px;\n"
                                   "\n"
                                   "color: rgb(151, 155, 158);")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_2.setGeometry(QtCore.QRect(70, 302, 280, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-1)
        self.label_2.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                   "padding-left: 5px;"
                                   "border-radius: 7px;\n"
                                   "\n"
                                   "color: rgb(151, 155, 158);")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_menu)
        self.label_4.setGeometry(QtCore.QRect(70, 419, 280, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setToolTipDuration(-1)
        self.label_4.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                   "padding-left: 5px;"
                                   "border-radius: 7px;\n"
                                   "\n"
                                   "color: rgb(151, 155, 158);")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.label_result = QtWidgets.QLabel(self.frame_menu)
        self.label_result.setGeometry(QtCore.QRect(140, 611, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                        "\n"
                                        "border-radius: 7px;\n"
                                        "\n"
                                        "color: rgb(255, 255, 255);")
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.label_score = QtWidgets.QLabel(self.frame_menu)
        self.label_score.setGeometry(QtCore.QRect(140, 651, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_score.setFont(font)
        self.label_score.setStyleSheet("background-color: rgb(98, 105, 111);\n"
                                       "\n"
                                       "border-radius: 7px;\n"
                                       "\n"
                                       "color: rgb(255, 255, 255);")
        self.label_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score.setText("")
        self.label_score.setObjectName("label_score")
        self.label_23 = QtWidgets.QLabel(self.frame_menu)
        self.label_23.setGeometry(QtCore.QRect(55, 660, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.label_21 = QtWidgets.QLabel(self.frame_menu)
        self.label_21.setGeometry(QtCore.QRect(55, 619, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.frame_menu)
        self.label_25.setGeometry(QtCore.QRect(55, 700, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_20 = QtWidgets.QLabel(self.frame_menu)
        self.label_20.setGeometry(QtCore.QRect(22, 613, 22, 26))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("icon/res.png"))
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.frame_menu)
        self.label_22.setGeometry(QtCore.QRect(20, 657, 25, 25))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("icon/score.png"))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.frame_menu)
        self.label_24.setGeometry(QtCore.QRect(22, 701, 25, 16))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("icon/loc.png"))
        self.label_24.setObjectName("label_24")
        self.tableWidget_info = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_info.setGeometry(QtCore.QRect(400, 610, 1181, 271))
        font = QtGui.QFont("Arial", 12)
        self.tableWidget_info.setFont(font)
        self.tableWidget_info.setStyleSheet("background-color: rgb(54, 63, 70);")
        # 设置网格线颜色
        self.tableWidget_info.setStyleSheet("QHeaderView::section { background-color: red; }")
        self.tableWidget_info.setLineWidth(0)
        # 启用横向纵向滑动条
        self.tableWidget_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        # 创建自定义滚动条并设置样式
        vertical_scrollbar = QScrollBar(Qt.Vertical, self.tableWidget_info)
        vertical_scrollbar.setStyleSheet("background-color: rgb(179, 211, 250);")

        # 将自定义滚动条设置给滚动区域
        self.tableWidget_info.setVerticalScrollBar(vertical_scrollbar)

        self.tableWidget_info.setColumnCount(8)
        self.tableWidget_info.setObjectName("tableWidget_info")
        self.tableWidget_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(0, item)
        self.tableWidget_info.setColumnWidth(0, 80)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(1, item)
        self.tableWidget_info.setColumnWidth(1, 293)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(2, item)
        self.tableWidget_info.setColumnWidth(2, 180)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(5, item)
        self.tableWidget_info.setColumnWidth(5, 180)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(6, item)
        self.tableWidget_info.setColumnWidth(6, 80)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(7, item)
        self.tableWidget_info.setColumnWidth(7, 150)
        self.tableWidget_info.horizontalHeader().setCascadingSectionResizes(False)
        # 选中时，表头无效果
        self.tableWidget_info.horizontalHeader().setHighlightSections(False)
        # self.tableWidget_info.horizontalHeader().setDefaultSectionSize(148)
        self.tableWidget_info.horizontalHeader().setMinimumSectionSize(30)
        # 设置表头的背景颜色
        self.tableWidget_info.horizontalHeader().setStyleSheet(
            "QHeaderView::section { background-color: rgb(179, 211, 250); }")
        # 禁用行号
        self.tableWidget_info.verticalHeader().setVisible(False)
        # 内容不可更改
        self.tableWidget_info.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 1601, 40))
        self.label_15.setStyleSheet("background-color: rgb(74, 160, 245);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(400, 100, 1181, 501))
        self.label_img.setStyleSheet("background-color: rgb(54, 63, 70);\n"
                                     "border-radius: 15px;")
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("icon/zhutu2.png"))
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 60, 115, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("icon/img.png"))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)

        self.label_logo = DraggableLabel(MainWindow)
        self.label_logo.setPixmap(QtGui.QPixmap("icon/app.png"))
        self.label_logo.setStyleSheet("background-color: rgb(74, 160, 245);")
        self.label_logo.setGeometry(QtCore.QRect(10, 5, 50, 35))
        self.label_logo.setObjectName("label_logo")

        self.label_11 = DraggableLabel(MainWindow)
        self.label_11.setGeometry(QtCore.QRect(55, 0, 250, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background: transparent;\n"
                                    "color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")


        #self.label_csdn_blog = DraggableLabel(MainWindow)
        #self.label_csdn_blog.setGeometry(QtCore.QRect(400, 3, 50, 37))
        #self.label_csdn_blog.setPixmap(QtGui.QPixmap("icon/CSDN.png"))
        #self.label_csdn_blog.setOpenExternalLinks(True)  # 允许打开外部链接
        #self.label_csdn_blog.setCursor(Qt.PointingHandCursor)  # 更改光标样式
        #self.label_csdn_blog.setStyleSheet("background-color: rgb(74, 160, 245);")
        # 设置网址超链接
        #url_blog = QUrl("https://blog.csdn.net/qq_28949847/article/details/130597656")
        #self.label_csdn_blog.setToolTip(url_blog.toString())
        # 博客点击
        #self.label_csdn_blog.mousePressEvent = lambda event: self.open_url(
        #    url_blog) if event.button() == Qt.LeftButton else None
        #
        # self.label_csdn_all = DraggableLabel(MainWindow)
        # self.label_csdn_all.setGeometry(QtCore.QRect(450, 0, 50, 40))
        # self.label_csdn_all.setPixmap(QtGui.QPixmap("icon/cam.png"))
        # self.label_csdn_all.setOpenExternalLinks(True)  # 允许打开外部链接
        # self.label_csdn_all.setCursor(Qt.PointingHandCursor)  # 更改光标样式
        # self.label_csdn_all.setStyleSheet("background-color: rgb(74, 160, 245);")
        # # # 设置网址超链接
        # url_all = QUrl("https://blog.csdn.net/qq_28949847/article/details/128552785")
        # self.label_csdn_all.setToolTip(url_all.toString())
        # # 博客点击
        # self.label_csdn_all.mousePressEvent = lambda event: self.open_url(
        #     url_all) if event.button() == Qt.LeftButton else None

        '''
        self.label_csdn_mbd = DraggableLabel(MainWindow)
        self.label_csdn_mbd.setGeometry(QtCore.QRect(450, 0, 50, 40))
        self.label_csdn_mbd.setPixmap(QtGui.QPixmap("icon/MBD.png"))
        self.label_csdn_mbd.setOpenExternalLinks(True)  # 允许打开外部链接
        self.label_csdn_mbd.setCursor(Qt.PointingHandCursor)  # 更改光标样式
        self.label_csdn_mbd.setStyleSheet("background-color: rgb(74, 160, 245);")
        # 设置网址超链接
        url_mbd = QUrl("https://mbd.pub/o/author-cGeYm2xm/work")
        self.label_csdn_mbd.setToolTip(url_mbd.toString())
        # 博客点击
        self.label_csdn_mbd.mousePressEvent = lambda event: self.open_url(
            url_mbd) if event.button() == Qt.LeftButton else None

        self.label_csdn_csdn_project = DraggableLabel(MainWindow)
        self.label_csdn_csdn_project.setGeometry(QtCore.QRect(500, 0, 50, 40))
        self.label_csdn_csdn_project.setPixmap(QtGui.QPixmap("icon/TB1.png"))
        self.label_csdn_csdn_project.setOpenExternalLinks(True)  # 允许打开外部链接
        self.label_csdn_csdn_project.setCursor(Qt.PointingHandCursor)  # 更改光标样式
        self.label_csdn_csdn_project.setStyleSheet("background-color: rgb(74, 160, 245);")
        # 设置网址超链接
        url_p = QUrl("https://blog.csdn.net/qq_28949847/category_12366752.html")
        self.label_csdn_csdn_project.setToolTip(url_p.toString())
        # 博客点击
        self.label_csdn_csdn_project.mousePressEvent = lambda event: self.open_url(
            url_p) if event.button() == Qt.LeftButton else None
        '''
        self.toolButton_exit = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_exit.setGeometry(QtCore.QRect(1550, 10, 23, 20))
        self.toolButton_exit.setStyleSheet("background: transparent")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/cha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon4)
        self.toolButton_exit.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(1500, 10, 23, 20))
        self.toolButton_2.setStyleSheet("background: transparent")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/fangda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon5)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(1450, 4, 23, 20))
        self.toolButton_3.setStyleSheet("background: transparent")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/heng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon6)
        self.toolButton_3.setObjectName("toolButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.ProjectPath = os.getcwd()  # 获取当前工程文件位置

    # 打开超链接
    def open_url(self, url):
        QDesktopServices.openUrl(url)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setProperty("setWindowFlags", _translate("MainWindow", "QtCore.Qt.FramelessWindowHint"))
        MainWindow.setProperty("setAttribute", _translate("MainWindow", "QtCore.Qt.WA_TranslucentBackground"))
        self.pushButton_start.setText(_translate("MainWindow", "开始运行 >"))
        self.pushButton_export.setText(_translate("MainWindow", "导出数据 >"))
        self.label.setText(_translate("MainWindow", " 选择车牌文件夹"))
        self.label_3.setText(_translate("MainWindow", " 选择车牌图片文件"))
        self.label_2.setText(_translate("MainWindow", " 选择车牌视频文件"))
        self.label_4.setText(_translate("MainWindow", " 已关闭摄像头"))
        self.label_23.setText(_translate("MainWindow", "Score:"))
        self.label_21.setText(_translate("MainWindow", "识别结果:"))
        self.label_25.setText(_translate("MainWindow", "车牌结果:"))
        item = self.tableWidget_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "图片名称"))
        item = self.tableWidget_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "录入时间"))
        item = self.tableWidget_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "车牌号码"))
        item = self.tableWidget_info.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "车牌类型"))
        item = self.tableWidget_info.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "车牌位置"))
        item = self.tableWidget_info.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget_info.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "车牌信息"))
        self.label_5.setText(_translate("MainWindow", "输入图像:"))
        self.label_11.setText(_translate("MainWindow", "车牌识别与管理系统"))
        self.toolButton_exit.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
